# Generated by Django 6.0.1 on 2026-01-12 09:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('descriere', models.TextField(blank=True)),
                ('imagine', models.ImageField(blank=True, null=True, upload_to='categorii/')),
                ('culoare', models.CharField(default='#928C8C', max_length=7)),
                ('icon_class', models.CharField(blank=True, max_length=20)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categorii',
            },
        ),
        migrations.CreateModel(
            name='IncercareLagare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('data_incercare', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Incercare Logare',
                'verbose_name_plural': 'Incercari Logare',
            },
        ),
        migrations.CreateModel(
            name='Producator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('tara_origine', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='producatori/')),
                ('descriere', models.TextField(blank=True)),
                ('activ', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Producatori',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('culoare', models.CharField(choices=[('#FF6B35', 'Portocaliu'), ('#00D9FF', 'Cyan'), ('#FFB700', 'Galben'), ('#00FF41', 'Verde'), ('#FF4136', 'Rosu'), ('#3498DB', 'Albastru')], default='#3498DB', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Tag-uri',
            },
        ),
        migrations.CreateModel(
            name='Utilizator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefon', models.CharField(blank=True, max_length=15, null=True)),
                ('adresa', models.CharField(blank=True, max_length=300, null=True)),
                ('oras', models.CharField(blank=True, max_length=100, null=True)),
                ('judet', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('data_nasterii', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('cod', models.CharField(blank=True, max_length=100, null=True)),
                ('email_confirmat', models.BooleanField(default=False)),
                ('blocat', models.BooleanField(default=False)),
                ('notificare_campuri_lipsa', models.BooleanField(default=False)),
                ('ultima_notificare_campuri', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilizator',
                'verbose_name_plural': 'Utilizatori',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_comanda', models.DateTimeField(auto_now_add=True)),
                ('stare', models.CharField(choices=[('asteptare', 'In asteptare'), ('procesare', 'In procesare'), ('expediat', 'Expediat'), ('livrat', 'Livrat'), ('anulat', 'Anulat')], default='asteptare', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adresa_livrare', models.TextField()),
                ('observatii', models.TextField(blank=True)),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comenzi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comanda',
                'verbose_name_plural': 'Comenzi',
                'ordering': ['-data_comanda'],
            },
        ),
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('descriere_scurta', models.CharField(blank=True, max_length=500)),
                ('descriere_lunga', models.TextField(blank=True)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pret_vechi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cod_produs', models.CharField(max_length=100, unique=True)),
                ('imagine', models.ImageField(upload_to='produse/')),
                ('stoc', models.IntegerField(default=0)),
                ('disponibil', models.BooleanField(default=True)),
                ('categorii', models.ManyToManyField(blank=True, related_name='produse', to='products.categorie')),
                ('producator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produse', to='products.producator')),
                ('tag_uri', models.ManyToManyField(blank=True, related_name='produse', to='products.tag')),
            ],
            options={
                'verbose_name_plural': 'Produse',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procent', models.IntegerField()),
                ('data_inceput', models.DateTimeField()),
                ('data_sfarsit', models.DateTimeField()),
                ('activ', models.BooleanField(default=True)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounturi', to='products.produs')),
            ],
            options={
                'verbose_name_plural': 'Discounturi',
                'ordering': ['-data_inceput'],
            },
        ),
        migrations.CreateModel(
            name='ProdusComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantitate', models.IntegerField(default=1)),
                ('pret_unitar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produse_comanda', to='products.comanda')),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.produs')),
            ],
            options={
                'verbose_name': 'Produs Comanda',
                'verbose_name_plural': 'Produse Comenzi',
            },
        ),
        migrations.CreateModel(
            name='Promotie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('data_creare', models.DateTimeField(auto_now_add=True)),
                ('data_expirare', models.DateTimeField()),
                ('descriere', models.TextField(blank=True)),
                ('procent_reducere', models.IntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('categorii', models.ManyToManyField(related_name='promotii', to='products.categorie')),
            ],
            options={
                'verbose_name': 'Promotie',
                'verbose_name_plural': 'Promotii',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'O stea'), (2, '2 stele'), (3, '3 stele'), (4, '4 stele'), (5, '5 stele')])),
                ('titlu', models.CharField(max_length=200)),
                ('comentariu', models.TextField()),
                ('nume_client', models.CharField(max_length=200)),
                ('verificat', models.BooleanField(default=False)),
                ('data_review', models.DateTimeField(auto_now_add=True)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='products.produs')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
                'ordering': ['-data_review'],
            },
        ),
        migrations.CreateModel(
            name='Specificatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('valoare', models.CharField(max_length=500)),
                ('ordine', models.IntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specificatii', to='products.produs')),
            ],
            options={
                'verbose_name_plural': 'Specificatii',
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='Vizualizare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vizualizare', models.DateTimeField(auto_now_add=True)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vizualizari', to='products.produs')),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vizualizari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vizualizare',
                'verbose_name_plural': 'Vizualizari',
                'ordering': ['-data_vizualizare'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(choices=[(1, '1 stele'), (2, '2 stele'), (3, '3 stele'), (4, '4 stele'), (5, '5 stele')])),
                ('data_notare', models.DateTimeField(auto_now_add=True)),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to=settings.AUTH_USER_MODEL)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='products.produs')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Note',
                'unique_together': {('utilizator', 'produs')},
            },
        ),
    ]
