# Generated by Django 5.2.7 on 2025-10-13 22:17

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('descriere', models.TextField(blank=True)),
                ('imagine', models.ImageField(blank=True, null=True, upload_to='categorii/')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categorii',
            },
        ),
        migrations.CreateModel(
            name='Producator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('tara_origine', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='producatori/')),
                ('descriere', models.TextField(blank=True)),
                ('activ', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Producatori',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('culoare', colorfield.fields.ColorField(default='#3498DB', image_field=None, max_length=25, samples=None)),
            ],
            options={
                'verbose_name_plural': 'Tag-uri',
            },
        ),
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('descriere_scurta', models.CharField(blank=True, max_length=500)),
                ('descriere_lunga', models.TextField(blank=True)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pret_vechi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cod_produs', models.CharField(max_length=100, unique=True)),
                ('imagine', models.ImageField(upload_to='produse/')),
                ('stoc', models.IntegerField(default=0)),
                ('disponibil', models.BooleanField(default=True)),
                ('categorii', models.ManyToManyField(blank=True, related_name='produse', to='products.categorie')),
                ('producator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produse', to='products.producator')),
                ('tag_uri', models.ManyToManyField(blank=True, related_name='produse', to='products.tag')),
            ],
            options={
                'verbose_name_plural': 'Produse',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procent', models.IntegerField()),
                ('data_inceput', models.DateTimeField()),
                ('data_sfarsit', models.DateTimeField()),
                ('activ', models.BooleanField(default=True)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounturi', to='products.produs')),
            ],
            options={
                'verbose_name_plural': 'Discounturi',
                'ordering': ['-data_inceput'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'O stea'), (2, '2 stele'), (3, '3 stele'), (4, '4 stele'), (5, '5 stele')])),
                ('titlu', models.CharField(max_length=200)),
                ('comentariu', models.TextField()),
                ('nume_client', models.CharField(max_length=200)),
                ('verificat', models.BooleanField(default=False)),
                ('data_review', models.DateTimeField(auto_now_add=True)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='products.produs')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
                'ordering': ['-data_review'],
            },
        ),
        migrations.CreateModel(
            name='Specificatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('valoare', models.CharField(max_length=500)),
                ('ordine', models.IntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specificatii', to='products.produs')),
            ],
            options={
                'verbose_name_plural': 'Specificatii',
                'ordering': ['ordine'],
            },
        ),
    ]
